# Generated by Django 3.1.6 on 2021-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='img',
            field=models.CharField(default=1, max_length=50, verbose_name='Img'),
            preserve_default=False,
        ),
    ]
