# Generated by Django 3.1.6 on 2021-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_basket_errors_favorite_otz_sale_saleproduct_salesname_statistic_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='number',
            field=models.CharField(max_length=50, verbose_name='nnn'),
        ),
    ]
