# Generated by Django 3.1.6 on 2021-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210205_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
            ],
        ),
    ]
